"""
Generates a role-specific, Kuvera-branded PDF weekly pulse note using fpdf2.
"""
import logging
import datetime
import os
from typing import List, Dict, Any
from fpdf import FPDF, XPos, YPos
from config.settings import OUTPUT_DIR, APP_NAME

logger = logging.getLogger("pdf_note")

# Kuvera Brand Colors (RGB)
BRAND_BLACK = (15, 15, 15)
BRAND_CYAN = (0, 209, 255)
BRAND_DARK_GREY = (45, 52, 54)
BRAND_LIGHT_GREY = (244, 247, 246)
WHITE = (255, 255, 255)
TEXT_MUTED = (99, 110, 114)

ROLE_CONTEXT = {
    "Product Team": {
        "tagline": "Engineering & Feature Prioritization Briefing",
        "intro": "Focus on these highest-priority user-reported issues for upcoming sprint planning. Themes are ranked by volume and severity.",
        "theme_label": "Engineering Priority",
        "action_label": "Recommended Sprint Items",
        "quote_label": "User-Reported Pain Points",
    },
    "Support Team": {
        "tagline": "Customer Escalation Preparedness Briefing",
        "intro": "Equip agents with these top complaint themes and user language to handle escalations with empathy and accuracy.",
        "theme_label": "Top Escalation Theme",
        "action_label": "Agent Action Points",
        "quote_label": "Real User Voices to Understand",
    },
    "Leadership": {
        "tagline": "Strategic Sentiment & Retention Risk Briefing",
        "intro": "Executive summary of critical signals from app reviews with strategic priorities for business impact.",
        "theme_label": "Retention Risk Area",
        "action_label": "Strategic Recommendations",
        "quote_label": "Representative User Sentiment",
    },
}


def _sanitize(text):
    """Replace non-Latin-1 characters so fpdf2 Helvetica can render them."""
    replacements = {
        '\u2605': '*',
        '\u2606': '*',
        '\u2014': '-',
        '\u2013': '-',
        '\u2018': "'",
        '\u2019': "'",
        '\u201C': '"',
        '\u201D': '"',
        '\u2026': '...',
        '\u2022': '-',
        '\u00b7': '-',
        '\u2003': ' ',
        '\u00a0': ' ',
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'replace').decode('latin-1')


class KuveraPDF(FPDF):
    def header(self):
        # Black header bar
        self.set_fill_color(*BRAND_BLACK)
        self.rect(0, 0, 210, 30, 'F')
        # Cyan accent line
        self.set_fill_color(*BRAND_CYAN)
        self.rect(0, 30, 210, 2, 'F')
        # Logo text
        self.set_xy(12, 6)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*WHITE)
        self.cell(30, 10, "KUVERA", new_x=XPos.RIGHT, new_y=YPos.TOP)
        self.set_text_color(*BRAND_CYAN)
        self.cell(20, 10, " PULSE", new_x=XPos.RIGHT, new_y=YPos.TOP)
        # Week date on the right
        self.set_font("Helvetica", "", 9)
        self.set_text_color(180, 180, 180)
        self.set_xy(120, 11)
        self.cell(78, 8, f"Weekly Pulse | {datetime.datetime.now().strftime('%B %d, %Y')}", align="R")

    def footer(self):
        self.set_y(-14)
        self.set_fill_color(*BRAND_BLACK)
        self.rect(0, self.get_y(), 210, 14, 'F')
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "CONFIDENTIAL | Generated by Kuvera Pulse AI Engine | Kuvera by CRED", align="C")

    def section_title(self, title: str):
        self.ln(6)
        # Cyan left bar
        self.set_fill_color(*BRAND_CYAN)
        self.rect(12, self.get_y(), 4, 7, 'F')
        self.set_xy(20, self.get_y())
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*BRAND_DARK_GREY)
        self.cell(0, 7, _sanitize(title.upper()), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(2)

    def theme_card(self, rank: int, name: str, volume: int, rating: float, label: str):
        name = _sanitize(name)
        label = _sanitize(label)
        x = self.get_x()
        y = self.get_y()
        card_h = 16
        card_w = 186

        # Card background
        self.set_fill_color(*BRAND_LIGHT_GREY)
        self.rect(12, y, card_w, card_h, 'F')

        # Rank badge
        self.set_fill_color(*BRAND_CYAN)
        self.rect(12, y, 10, card_h, 'F')
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*BRAND_BLACK)
        self.set_xy(12, y + 3)
        self.cell(10, 10, str(rank), align="C")

        # Theme name
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*BRAND_DARK_GREY)
        self.set_xy(26, y + 2)
        self.cell(100, 6, name)

        # Label
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*TEXT_MUTED)
        self.set_xy(26, y + 9)
        self.cell(100, 5, label)

        # Stats on right
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*BRAND_DARK_GREY)
        self.set_xy(140, y + 2)
        self.cell(58, 6, _sanitize(f"{volume} reviews  |  {rating}/5 *"), align="R")

        self.set_xy(12, y + card_h + 2)

    def quote_block(self, quote: str, index: int):
        quote = _sanitize(quote)
        self.set_fill_color(235, 250, 255)
        y = self.get_y()
        # Left accent
        self.set_fill_color(*BRAND_CYAN)
        self.rect(12, y, 3, 1, 'F')  # will be overwritten by multiline height
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(*BRAND_DARK_GREY)
        self.set_xy(18, y)
        self.set_fill_color(240, 252, 255)
        # Calculate height
        quoted_text = '"' + quote + '"'
        lines = self.get_string_width(quoted_text) // 170 + 1
        h = max(10, int(lines) * 6 + 4)
        self.rect(12, y, 186, h, 'F')
        self.set_fill_color(*BRAND_CYAN)
        self.rect(12, y, 3, h, 'F')
        self.set_xy(18, y + 2)
        self.multi_cell(178, 5, quoted_text)
        self.ln(2)

    def action_item(self, index: int, text: str):
        text = _sanitize(text)
        y = self.get_y()
        self.set_fill_color(*BRAND_CYAN)
        self.ellipse(13, y + 2, 5, 5, 'F')
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*WHITE)
        self.set_xy(13, y + 1.5)
        self.cell(5, 5, str(index), align="C")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*BRAND_DARK_GREY)
        self.set_xy(22, y)
        self.multi_cell(176, 6, _sanitize(text))
        self.ln(1)


def generate_pdf_note(role: str, insights_data: dict, action_ideas: list, output_path: str):
    """Generate a branded, role-specific PDF pulse note."""
    try:
        local_clusters = insights_data.get("local_clusters", {})
        sorted_themes = sorted(local_clusters.items(), key=lambda x: x[1].get("volume", 0), reverse=True)[:3]
        total_reviews = sum(d.get("volume", 0) for _, d in local_clusters.items())

        # If no clusters exist, create placeholder themes so the PDF is still useful
        if not sorted_themes:
            sorted_themes = [
                ("App Performance & Stability", {"volume": 0, "average_rating": 0, "representative_quotes": ["Data pending - please run a fresh weekly pulse to populate insights."]}),
                ("User Experience & Navigation", {"volume": 0, "average_rating": 0, "representative_quotes": ["No review data available yet for this cycle."]}),
                ("Feature Requests & Improvements", {"volume": 0, "average_rating": 0, "representative_quotes": ["Awaiting new review data ingestion."]}),
            ]
            total_reviews = 0

        # Collect top 3 quotes
        all_quotes = []
        for _, data in sorted_themes:
            all_quotes.extend(data.get("representative_quotes", []))
        all_quotes = [q for q in all_quotes if q and len(q.strip()) > 10][:3]
        while len(all_quotes) < 3:
            all_quotes.append("Users are experiencing friction with core app features after the recent update.")

        # Clean action_ideas — remove markdown bold markers and intro sentences
        clean_actions = []
        import re
        for idea in action_ideas:
            # Skip intro sentences (usually long, no colon, contains 'action ideas' or 'team')
            if len(idea) > 60 and ":" not in idea and ("action ideas" in idea.lower() or "team" in idea.lower()):
                continue
            
            # Clean formatting
            cleaned = idea.replace("**", "").strip()
            # Remove leading numbers like "1. "
            cleaned = re.sub(r'^\d+[\.\)]\s*', '', cleaned)
            
            if cleaned and len(cleaned) > 5:
                clean_actions.append(cleaned)
        
        # If we have too many, take the first 3. If too few, add placeholders.
        actions = clean_actions[:3]
        while len(actions) < 3:
            actions.append("Prioritize reported friction points in the next operational cycle.")

        ctx = ROLE_CONTEXT.get(role, ROLE_CONTEXT["Leadership"])

        pdf = KuveraPDF()
        pdf.set_auto_page_break(auto=True, margin=25) # Increased bottom margin to prevent footer overlap
        pdf.add_page()
        pdf.set_margins(12, 40, 12) # Increased top margin to 40 to clear header (which is 32)

        # Role header
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(*BRAND_DARK_GREY)
        pdf.set_y(40) # Explicitly set y to top margin
        pdf.set_x(12)
        pdf.cell(0, 8, _sanitize(f"Weekly Pulse Note - {role}"), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*TEXT_MUTED)
        pdf.cell(0, 5, _sanitize(ctx["tagline"]), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Stats bar
        pdf.ln(3)
        pdf.set_fill_color(*BRAND_BLACK)
        pdf.rect(12, pdf.get_y(), 186, 12, 'F')
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*WHITE)
        pdf.set_xy(16, pdf.get_y() + 2)
        pdf.cell(60, 7, f"  {total_reviews} Reviews Analyzed")
        pdf.cell(60, 7, f"   Week of {datetime.datetime.now().strftime('%B %d, %Y')}")
        pdf.cell(60, 7, f"   For: {role}", align="R")
        pdf.ln(14)

        # Intro
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*BRAND_DARK_GREY)
        pdf.set_x(12)
        pdf.multi_cell(186, 6, _sanitize(ctx["intro"]))

        # Top 3 themes
        pdf.section_title(f"Top 3 {ctx['theme_label']}s This Week")
        for i, (name, data) in enumerate(sorted_themes, 1):
            pdf.theme_card(i, _sanitize(name), data.get("volume", 0), data.get("average_rating", 0), ctx["theme_label"])
        pdf.ln(4)

        # 3 user quotes
        pdf.section_title(ctx["quote_label"])
        for q in all_quotes:
            pdf.quote_block(q, 0)

        # 3 actions
        pdf.section_title(ctx["action_label"])
        for i, action in enumerate(actions, 1):
            pdf.action_item(i, action)

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pdf.output(output_path)
        logger.info(f"PDF note generated: {output_path}")
        return True
    except Exception as e:
        logger.error(f"Failed to generate PDF for {role}: {e}")
        return False


def generate_all_pdf_notes(insights_data: dict, action_ideas: list) -> Dict[str, str]:
    """Generate PDF notes for all 3 roles. Returns {role: filepath}."""
    today_str = datetime.datetime.now().strftime("%Y%m%d")
    paths = {}
    for role in ["Product Team", "Support Team", "Leadership"]:
        filename = f"Kuvera_Pulse_{role.replace(' ', '_')}_{today_str}.pdf"
        output_path = str(OUTPUT_DIR / filename)
        success = generate_pdf_note(role, insights_data, list(action_ideas), output_path)
        if success:
            paths[role] = output_path
    return paths
